config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'movies#index'

  resources :movies do
    resources :reviews
    collection do
      get 'search'
    end
  end
  
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord

  mount_uploader :image, ImagesUploader
  
  has_many :reviews
  has_many :users, through: :reviews

  validates :title, :director, :image, presence: true

  def self.search(search)
    if search
      Movie.where(['title LIKE(?) or director LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      Movie.all
    end
  end
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  validates :body, :rating, presence: true
  validates_uniqueness_of :movie_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :movies, through: :reviews

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_movie, only: [:edit, :update, :show, :destroy]

  def index
    @movies = Movie.all.order("created_at DESC")
  end

  def show
    if @movie.reviews.blank?
      @average_review = 0
    else
      @average_review = @movie.reviews.average(:rating).round(2)
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.create(movie_params)
    if @movie.save
      redirect_to root_path
    else
      redirect_to new_movie_path
    end
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
      redirect_to root_path
    else
      redirect_to edit_movie_path
    end
  end

  def search
    @movies = Movie.search(params[:keyword]).order("created_at DESC")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def destroy
    if @movie.destroy
      redirect_to root_path
    else
      redirect_to movie_path
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :director, :image)
  end

  def set_movie
    @movie = Movie.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_movie, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_review, only: [:edit, :update, :destroy]


  def new
    @review = Review.new
  end

  def create
    @review = Review.new(
      body: review_params[:body],
      user_id: current_user.id,
      movie_id: params[:movie_id],
      rating: review_params[:rating],
    )

    if @review.save
      redirect_to movie_path(@review.movie)
    else
      redirect_to new_movie_review_path
    end
  end

  def edit
  end

  def update
    if @review.update(
      body: review_params[:body],
      user_id: current_user.id,
      movie_id: params[:movie_id],
      rating: review_params[:rating],
    )
      redirect_to movie_path(@review.movie)
    else
      redirect_to edit_movie_review_path
    end
  end

  def destroy
    if @review.destroy
      redirect_to movie_path(@review.movie)
    else
      redirect_to edit_movie_review_path
    end
  end

  private
  
  def review_params
    params.require(:review).permit(:body, :movie_id, :user_id, :rating)
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :forbid_test_user, {only: [:edit,:update]}

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end

  def forbid_test_user
    if current_user.email == "test@gmail.com"
      flash[:notice] = "テストユーザーのため変更できません"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.haml
= render "/shared/header"

.write-contents
  .container
    = form_for [@movie] do |f|
      .container__title
        %h2 Edit Movie
      .container__text
        = f.label :タイトル
        = f.text_field :title, class: 'input-default', placeholder: '映画のタイトルを入力してください'
        = f.label :監督
        = f.text_field :director, class: 'input-default', placeholder: '監督名を入力してください'
        = f.label :映画の画像
        - if @movie.image.present?
          = image_tag @movie.image.url, id: :img_prev,size: "200x250"
        - else
          = image_tag "NoImage.png", id: :img_prev,size: "100x150"
        = f.file_field :image,class: 'image-default',id: :note_img
        = f.submit '更新する', class: 'write-btn'
        
= render "/shared/footer"

app/views/movies/index.html.haml
.header
  .header-container
    .header-title
      = link_to root_path do
        = icon('fas', 'video', class: 'mypage-icon')
        MovieLovers
    .header-box
      .header-box__search
        = form_with(url: search_movies_path, local: true, method: :get) do |f|
          = f.text_field :keyword,placeholder: "タイトルor監督名で検索",class: "search-form"
          = button_tag type: 'submit', class: "search-box" do
            = icon('fas', 'search')
      .header-box__mypage
        - if user_signed_in?
          - if current_user.email == "test@gmail.com"
            = link_to destroy_user_session_path, method: :delete do
              = icon('fas', 'sign-out-alt', class: 'mypage-icon')
          - else 
            = link_to edit_user_path(current_user) do
              = icon('fas', 'user', class: 'mypage-icon')
        - else
          = link_to new_user_registration_path do
            = icon('fas', 'user', class: 'mypage-icon')

.main
  .main-container
    .main-name
      Movie List
    .movies
      - @movies.each do |movie|
        .movie
          = link_to movie_path(movie) do
            = image_tag movie.image.url,class: "movie-image" ,size: "200x250" if movie.image.present?


.post
  = link_to new_movie_path do
    .post__text
      Create-Movie
      = icon('fas', 'film', class: 'icon')

= render "/shared/footer"

app/views/movies/new.html.haml
= render "/shared/header"

.write-contents
  .container
    = form_for [@movie] do |f|
      .container__title
        %h2 Create Movie
      .container__text
        = f.label :タイトル
        = f.text_field :title, class: 'input-default', placeholder: '映画のタイトルを入力してください'
        = f.label :監督
        = f.text_field :director, class: 'input-default', placeholder: '監督名を入力してください'
        = f.label :映画の画像
        - if @movie.image.present?
          = image_tag @movie.image.url, id: :img_prev,size: "200x250"
        - else
          = image_tag "NoImage.png", id: :img_prev,size: "100x150"
        = f.file_field :image,class: 'image-default',id: :note_img
        = f.submit '映画を作成', class: 'write-btn'
        
= render "/shared/footer"

app/views/movies/search.html.haml
.header
  .header-container
    .header-title
      = link_to root_path do
        = icon('fas', 'video', class: 'mypage-icon')
        MovieLovers
    .header-box
      .header-box__search
        = form_with(url: search_movies_path, local: true, method: :get) do |f|
          = f.text_field :keyword,placeholder: "タイトルor監督名で検索",class: "search-form"
          = button_tag type: 'submit', class: "search-box" do
            = icon('fas', 'search')
      .header-box__mypage
        - if user_signed_in?
          - if current_user.email == "test@gmail.com"
            = link_to destroy_user_session_path, method: :delete do
              = icon('fas', 'sign-out-alt', class: 'mypage-icon')
          - else 
            = link_to edit_user_path(current_user) do
              = icon('fas', 'user', class: 'mypage-icon')
        - else
          = link_to new_user_registration_path do
            = icon('fas', 'user', class: 'mypage-icon')

.main
  .main-container
    .main-name
      Movie List
    .movies
      - @movies.each do |movie|
        .movie
          = link_to movie_path(movie) do
            = image_tag movie.image.url,class: "movie-image" ,size: "200x250" if movie.image.present?


.post
  = link_to new_movie_path do
    .post__text
      Create-Movie
      = icon('fas', 'film', class: 'icon')

= render "/shared/footer"

app/views/movies/show.html.haml
= render "/shared/header"

.show-contents
  .show-container
    .show-image
      = image_tag @movie.image.url, size: "250x300"
      .average-review-rating{"data-score": @average_review}
    .show-text
      = link_to 'ムービーの内容を編集する', edit_movie_path(@movie),class: "edit-btn"
      = link_to 'ムービーを削除する',"/movies/#{@movie.id}", method: :delete, class: "delete-btn" 
    .show-text
      .left-title
        タイトル
      .right-text
        = @movie.title
    .show-text
      .left-title
        監督
      .right-text
        = @movie.director
    .show-review
      .left-title
        レビュー
      .right-text
        - if @movie.reviews.count > 0
          %h2 
            = "投稿されたレビュー#{@movie.reviews.count}件"
          - @movie.reviews.each do |review|
            .review-box
              .review-box__username
                = "投稿者 : #{review.user.nickname}さん"
              .review-box__body
                .review-rating{"data-score": review.rating}
                = simple_format(review.body)
              - if current_user == review.user
                = link_to "編集", "/movies/#{@movie.id}/reviews/#{review.id}/edit",class: "review-edit"
                = link_to "削除", "/movies/#{@movie.id}/reviews/#{review.id}",method: :delete, class: "review-delete"
        - else
          %h2 
            投稿されたレビューはありません
.post-review
  = link_to new_movie_review_path(@movie) do
    .post-review__text
      レビューを投稿する
      = icon('fas', 'smile-beam', class: 'icon')
      

= render "/shared/footer"

:javascript
  $('.review-rating').raty({
  	readOnly: true,
  	score: function() {
  		return $(this).attr('data-score');
  	},
  	path: '/assets/'
  });

:javascript
  $('.average-review-rating').raty({
  	readOnly: true,
  	path: '/assets/',
  	score: function() {
  		return $(this).attr('data-score')
  	}
  });

app/views/reviews/edit.html.haml
= render "/shared/header"

.review-contents
  .review-container
    .review-title
      = "「#{@movie.title}」へのレビューを編集"
    .review-image
      = image_tag @movie.image.url, size: "250x300"
    .review-text
      = form_for [@movie, @review] do |f|
        - if @review.errors.any?
          - @review.errors.full_messages.each do |msg|
            %li{style: "color: red;"}
              = msg
        .contents
          レビュー内容
        .rating 
          レーティング
        #rating-form
        = f.label :コメント, class:'comment'
        = f.text_area :body, class:'input'
        = f.submit '更新する', class: 'btn'
 
      

= render "/shared/footer"

:javascript
  $('#rating-form').raty({
  	path: '/assets/',
  	scoreName: 'review[rating]'
  });

app/views/reviews/new.html.haml
= render "/shared/header"

.review-contents
  .review-container
    .review-title
      = "「#{@movie.title}」への新規レビュー"
    .review-image
      = image_tag @movie.image.url, size: "250x300"
    .review-text
      = form_for [@movie, @review] do |f|
        - if @review.errors.any?
          - @review.errors.full_messages.each do |msg|
            %li{style: "color: red;"}
              = msg
        .contents
          レビュー内容
        .rating 
          レーティング
        #rating-form
        = f.label :コメント, class:'comment'
        = f.text_area :body, class:'input'
        = f.submit '投稿する', class: 'btn'
 
      

= render "/shared/footer"

:javascript
  $('#rating-form').raty({
  	path: '/assets/',
  	scoreName: 'review[rating]'
  });

app/views/shared/_footer.html.haml
.write-footer
  .footer-container
    .footer-title
      = link_to root_path do
        = icon('fas', 'video', class: 'mypage-icon')
        MovieLovers

app/views/shared/_header.html.haml
.write-header
  .header-container
    .header-title
      = link_to root_path do
        = icon('fas', 'video', class: 'mypage-icon')
        MovieLovers

app/views/users/edit.html.haml
= render "/shared/header"

.single-main
  .login-single-container
    .login-single-head
      = link_to destroy_user_session_path, method: :delete,class: "user-newsession" do
        ログアウト
    = form_for(current_user,class: "login-single-innner") do |f|
      .login-single-content
        %h2 ユーザー情報を編集
        .form-group
          = f.label :ニックネーム
          = f.text_field :nickname, autofocus: true, placeholder: "ニックネーム",required: "required", class: 'login-input-default'
        .form-group
          = f.label :メールアドレス
          = f.text_field :email, autofocus: true, placeholder: "メールアドレス",required: "required", class: 'login-input-default'
        .form-group
          = f.submit "更新する", class: "user-login"

= render "/shared/footer"